services:
  - type: web
    name: ecotrip-planner
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OWM_API_KEY
        sync: false
